# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    url: '#about'
  - name: Venue
    url: '#venue'
    weight: 20
  - name: Application
    url: '#application'
    weight: 25
  - name: Program
    url: '#program'
    weight: 30
  - name: FAQ
    url: '#faq'
    weight: 35
  - name: Contributors
    url: '#people'
    weight: 40
  - name:  Past Editions
    url: '#past_editions'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 70
